'use strict';

const TextModules = {
    EN: {
        Intro1: "HI FRIENDS! I'M\nPROFESSOR DAVIS GREEN.\nWILL YOU HELP ME PREVENT\nSTORMWATER POLLUTION?",
        Intro2: "STORMWATER\nIS WATER THAT FLOWS\nACROSS THE GROUND\nWHEN IT RAINS.",
        Intro3_1: "STORMWATER RUNOFF\nCAN PICK UP POLLUTANTS\nAS IT FLOWS DOWN GUTTERS\nAND INTO STORMDRAIN\nINLETS IN THE STREET.",
        Intro3_2: "POLLUTANTS ARE THINGS\nTHAT MAKE WATER DIRTY.",
        Intro4_1: "STORMWATER IS NOT\nCLEANED. IT ISN'T TREATED\nBEFORE IT FLOWS TO\nLOCAL CREEKS, WETLANDS\nAND LOCAL WATERWAYS.",
        Intro4_2: "POLLUTED, DIRTY WATER\nCAN MAKE FISH AND\nANIMALS SICK.",
        Intro5: "LET'S SEE HOW THE SIMPLE\nCHOICES YOU MAKE AFFECT\nTHE WATER QUALITY IN\nLOCAL WETLANDS\nAND WATERWAYS."
    }
};